.TH PACFINDER "1" "Feb 2022" "PacFinder" "User Commands"
.SH NAME
PacFinder \- Repository & package explorer for Arch Linux.
.SH SYNOPSIS
.B pacfinder
[\fIoptions\fR]
.SH DESCRIPTION
\fBPacFinder\fP is a GTK 3 desktop application for browsing packages installed on your
Arch Linux system as well as exploring packages in the Arch Linux official
package repositories.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.TP
\fB\-\-help-all\fR
Show all help options
.TP
\fB\-\-help-gapplication\fR
Show GApplication options
.TP
\fB\-\-help-gtk\fR
Show GTK+ Options
.SH AUTHOR
Written by Steven Benner.
.SH BUGS
Please report bugs to
https://github.com/stevenbenner/pacfinder/issues
